tpretty and prettifier fixes according to luacheck warnings
lua-nucleo/lua-nucleo pull request #100
Opened 2021-04-01 09:57 UTC by E-Fir

2021-04-09 12:40 UTC, agladysh requested changes

2021-04-09 12:40 UTC, agladysh commented on lua-nucleo/prettifier.lua
> +      if father_table_pos > 0 and
разбито не по гайдлайнам

2021-04-09 12:40 UTC, agladysh commented on lua-nucleo/prettifier.lua
> +        pos, level, stype = positions[i], levels[i], types[i]
подозрительно!

2021-04-09 12:40 UTC, agladysh commented on lua-nucleo/tpretty.lua
> -  local add = ""
подать отдельным МР и влить

2021-04-12 09:11 UTC, E-Fir commented on lua-nucleo/tpretty.lua
> -  local add = ""
https://github.com/lua-nucleo/lua-nucleo/pull/101

2021-04-12 09:35 UTC, E-Fir commented on lua-nucleo/prettifier.lua
> +      if father_table_pos > 0 and
исправлено

2021-04-12 09:35 UTC, E-Fir commented on lua-nucleo/prettifier.lua
> +        pos, level, stype = positions[i], levels[i], types[i]
да, чушь была написана, исправлено

2021-04-12 11:22 UTC, merged