Color tpretty
lua-nucleo/lua-nucleo pull request #109
Opened 2021-04-16 09:23 UTC by E-Fir

2021-04-19 10:21 UTC, agladysh requested changes

2021-04-19 10:21 UTC, agladysh commented on lua-nucleo/prettifier.lua
> +        if prettifier.colors and prettifier.colors[color_id]
разбиение не по гайдлайнам

2021-04-19 10:21 UTC, agladysh commented on lua-nucleo/prettifier.lua
> +          and prettifier.colors.reset_color then
отсутствие reset — дефект
если задали хоть один цвет, обязаны задать и ресет
(боремся с тем, что без ресета все порвется)

2021-04-19 10:21 UTC, agladysh commented on lua-nucleo/prettifier.lua
>  local make_prettifier
добавь плз хотя бы заглушку LDoc-а

2021-04-19 10:21 UTC, agladysh commented on lua-nucleo/prettifier.lua
> +          and prettifier.colors.reset_color then
нужно добавить на это тест

2021-04-22 10:39 UTC, E-Fir commented on lua-nucleo/prettifier.lua
> +        if prettifier.colors and prettifier.colors[color_id]
исправлено в нойвой версии

2021-04-22 10:39 UTC, E-Fir commented on lua-nucleo/prettifier.lua
> +          and prettifier.colors.reset_color then
сделано

2021-04-22 10:39 UTC, E-Fir commented on lua-nucleo/prettifier.lua
>  local make_prettifier
добавил

2021-04-22 10:41 UTC, merged