HISTORY: add entry for 1.1.0 release
lua-nucleo/lua-nucleo pull request #112
Opened 2021-04-23 12:18 UTC by E-Fir

2021-04-23 12:23 UTC, E-Fir commented
```
git shortlog v1.0.0..HEAD

Alexander Gladysh (10):
      make.sh: more strict bash
      make.sh: updating list-exports only if a rock is installed
      test/test.lua: whitespace
      test/test.lua: redundant variable declaration removed
      tdeepequals/tless_kv: tmore does not need vis* initialization anymore
      tdeepequals/tmore: always initializing p_table to prevent crashes in tless
      dsl/common_load_schema: a heuristics to find a source location for dsl node
      dsl/dsl_loader: whitespace
      lua-nucleo/table-utils: tdeepfilter
      COPYRIGHT: updated year

Alexey Romanoff (110):
      fix 'unpack' in various modules for Lua 5.4
      test/test-lib/generate-test-list: fix lib_file
      test/cases/{0420-code-foreign-globals-luajit2, 0430-code-foreign-globals-lua5_1}: pass tests if cannot load lua-aplicado shell module
      strict: add 'newproxy' to globals
      test/cases/0080-functional: pass tests dependent on newproxy if newproxy not found
      strict: declare globals for Lua versions compatibility: loadstring and setfenv
      language: update to support all current Lua versions >= 5.1
      tpretty, tserialize, tstr: replace lua51_keywords with lua_keywords
      args, type, typeassert: replace lua51_types with lua_types
      language: add documentation block
      doc: regenerated
      test/test: add footer for failed low-level tests error messages dump
      test/test: use ad-hoc shell_read if lua-aplicado.shell not found
      test/low-level/0150-strict: fix broken test
      test/suite: add 0174-suite-BROKEN_IF
      test/data/suite: add suites for BROKEN_IF tests
      test/test-list: regenerated
      lua-nucleo/suite: add BROKEN_IF
      lua-nucleo/suite: store test name in the test instance
      lua-nucleo/suite: allow test_for chains
      lua-nucleo/suite: fix tests_for
      test/cases/0120-misc: fix tests with newproxy for Lua > 5.1
      test/test-lib/value_generators: throw error if newproxy not found
      test/test-lib/value_generators: fix formatting
      test/cases/0130-priority_queue: fix tests dependent on newproxy for Lua > 5.1
      test/cases/0130-priority_queue: fix formatting
      test/cases/0160-string: mark "tjson_simple" test as BROKEN if newproxy is not found
      test/cases/0190-table-utils: mark "tclone-nontable" test as BROKEN if newproxy is not found
      test/cases/0204-tdeepequals-userdata-functions-threads: mark tests as BROKEN if newproxy is not found
      test/cases/0240-type: mark "all_predicates" test as BROKEN if newproxy is not found
      test/cases/0250-typeassert: mark "all_assertions" test as BROKEN if newproxy is not found
      test/cases/0290-tstr: mark tests that dependent of newproxy as BROKEN if newproxy not found
      test/cases/0080-functional: use BROKEN_IF for tests that use newproxy
      test/low-level/0150-strict: expect declared globals for Lua versions compatibility: loadstring and setfenv
      add legacy module tests: 0650-legacy
      add legacy module
      test/test-list: regenerated
      test/cases: sets loadstring analog if loadstring is not found
      lua-nucleo/sandbox: fix loadstring for Lua > 5.1, add debug_traceback to locals
      test/test-lib/tserialize-test-utils: fix loadstring for Lua > 5.1
      lua-nucleo/ensure: add ldoc stubs to exported functions
      lua-nucleo/table-utils: add ldoc stubs to exported module members
      lua-nucleo/ensure: add ensure_strvariant; test/cases/0270-ensure: add tests for ensure_strvariant
      lua-nucleo/ensure: add ensure_strlist; test/cases/0270-ensure: add ensure_strlist to untested
      lua-nucleo/table-utils: add tifindallpermutations; test/cases/0190-table-utils: add tifindallpermutations tests
      lua-nucleo/ensure: add ensure_strpermutations; test/cases/0270-ensure: add ensure_strpermutations tests
      doc: regenerated
      lua-nucleo/init: export standard module metadata fields
      README: the "Documentation" section is updated
      README: the "Dependencies" section is updated
      make.sh: allow local luarocks installation with "--local" option
      add RELEASE instructions
      test/suite/0171-suite-full: fix Complex factory function input test 2
      args: fix argument number format in error messages
      test/cases/0270-ensure: fix ensure_error_with_substring-is-happy-on-failure and ensure_error-is-happy-on-failure tests
      lua-nucleo/tstr: fix serialization with metatables
      add lua-nucleo/datetime-utils module
      add lua-nucleo/enumenator module
      lua-nucleo/suite, test/data/suite: add test:DEPRECATED feature
      test/cases/0330-tpretty: fix tpretty_ex-bug-concat-nil-full test
      test/cases/0160-string: fix kv_concat tests
      test/cases/0160-string: fix tjson_simple test
      test/cases/{0420-code-foreign-globals-luajit2, 0430-code-foreign-globals-lua5_1}: tests are BROKEN_IF cannot load lua-aplicado shell module
      lua-nucleo/timestamp: add ldoc stubs
      lua-nucleo/timestamp, test/cases/0320-timestamp: add unpack_timestamp
      lua-nucleo/timestamp, test/cases/0320-timestamp: add make_timestamp_from_string
      lua-nucleo/timestamp, test/cases/0320-timestamp: add MAX_TIMESTAMP
      test/cases/0120-misc: add comments about failed test for unique_object, add BROKEN_IF condition
      0470-dsl-dsl_loader: add comments about failed tests, add BROKEN_IF conditions
      lua-nucleo/deque: fix pop_back
      test/cases/0190-table-utils: fix tflip_inplace-many
      lua-nucleo/tstr: fix serializing linear arrays with gaps
      test/cases/0290-test: fix "tstr table with keys" test
      lua-nucleo/tserialize: replace ipairs to fix serialization with holes in Lua >= 5.3
      etc/rockspec/generate: update Lua version constraints
      etc/rockspec/generate: use second comman line argument as the branch name for source
      RELEASE: update the example of the version rockspec generation
      RELEASE: "Regenerate tests list", "Last check that all tests are passed OK" steps are added
      RELEASE: add "checking the authors" step
      RELEASE: fix grammar
      add luacheck configuration (.luacheckrc)
      add luacheck runner (luacheck.sh)
      tpretty: remove unused variables
      .luacheckrc: ignore unused 'self' arguments
      prettifier: fix according to luacheck warnings
      prettifier: fix quotes style
      tpretty: fix quotes style
      tpretty: remove excessive 'local' statement for already defined variable
      {tpretty, test/cases/0330-tpretty}: fix serializing tables with overloaded __index
      prettifier: make_prettifier: check argument types
      prettifier: make_prettifier: add colors argument, check and store it in instance
      prettifier: add 'cat' function for adding to the buffer
      prettifier: add local 'make_colorizer' function: hook factory for adding color sequences
      prettifier: add local 'make_color_resetter' function: hook factory for adding reset color sequences
      prettifier: add colorizing to 'key_start' hook
      prettifier: add 'key_finish' hook
      prettifier: add 'string_start' and 'string_finish', 'number_start', 'number_finish', 'boolean_start', 'boolean_finish' hooks
      prettifier: add 'before_open_curly_brace' and 'before_closed_curly_brace', 'after_open_curly_brace', 'after_closed_curly_brace' hooks
      tpretty: add colors as the last argument to tpretty, tpretty_ex, tpretty_ordered; pass colors to prettifier factory
      tpretty: add 'key_finish' hook call
      tpretty: add 'string_start' and 'string_finish', 'number_start', 'number_finish', 'boolean_start', 'boolean_finish' hook calls
      prettifier: add curly braces hooks calls
      tpretty: disable colors for when rendering table key name
      test/cases: add 0333-tpretty-color
      prettifier: add ldoc comments
      tpretty: add ldoc comments
      tdeepequals: add ldoc comments for ordered_pairs, and ldoc comment stubs for the rest
      AUTHORS: actualize e-mail
      AUTHORS: sort the list for better check [...]

2021-04-23 12:24 UTC, E-Fir commented
отсортированное:
```
.luacheckrc: ignore unused 'self' arguments
0470-dsl-dsl_loader: add comments about failed tests, add BROKEN_IF conditions
AUTHORS: actualize e-mail
AUTHORS: add missing authors
AUTHORS: sort the list for better checking for the author
COPYRIGHT: updated year
README: the "Dependencies" section is updated
README: the "Documentation" section is updated
RELEASE: "Regenerate tests list", "Last check that all tests are passed OK" steps are added
RELEASE: add "checking the authors" step
RELEASE: fix grammar
RELEASE: update the example of the version rockspec generation
add RELEASE instructions
add legacy module
add legacy module tests: 0650-legacy
add lua-nucleo/datetime-utils module
add lua-nucleo/enumenator module
add luacheck configuration (.luacheckrc)
add luacheck runner (luacheck.sh)
args, type, typeassert: replace lua51_types with lua_types
args: fix argument number format in error messages
doc: regenerated
doc: regenerated
dsl/common_load_schema: a heuristics to find a source location for dsl node
dsl/dsl_loader: whitespace
etc/rockspec/generate: update Lua version constraints
etc/rockspec/generate: use second comman line argument as the branch name for source
fix 'unpack' in various modules for Lua 5.4
language: add documentation block
language: update to support all current Lua versions >= 5.1
lua-nucleo/deque: fix pop_back
lua-nucleo/ensure: add ensure_strlist; test/cases/0270-ensure: add ensure_strlist to untested
lua-nucleo/ensure: add ensure_strpermutations; test/cases/0270-ensure: add ensure_strpermutations tests
lua-nucleo/ensure: add ensure_strvariant; test/cases/0270-ensure: add tests for ensure_strvariant
lua-nucleo/ensure: add ldoc stubs to exported functions
lua-nucleo/init: export standard module metadata fields
lua-nucleo/sandbox: fix loadstring for Lua > 5.1, add debug_traceback to locals
lua-nucleo/suite, test/data/suite: add test:DEPRECATED feature
lua-nucleo/suite: add BROKEN_IF
lua-nucleo/suite: allow test_for chains
lua-nucleo/suite: fix tests_for
lua-nucleo/suite: store test name in the test instance
lua-nucleo/table-utils: add ldoc stubs to exported module members
lua-nucleo/table-utils: add tifindallpermutations; test/cases/0190-table-utils: add tifindallpermutations tests
lua-nucleo/table-utils: tdeepfilter
lua-nucleo/table-utils: tisarray_not
lua-nucleo/timestamp, test/cases/0320-timestamp: add MAX_TIMESTAMP
lua-nucleo/timestamp, test/cases/0320-timestamp: add make_timestamp_from_string
lua-nucleo/timestamp, test/cases/0320-timestamp: add unpack_timestamp
lua-nucleo/timestamp: add ldoc stubs
lua-nucleo/tserialize: replace ipairs to fix serialization with holes in Lua >= 5.3
lua-nucleo/tstr: fix serialization with metatables
lua-nucleo/tstr: fix serializing linear arrays with gaps
make.sh: allow local luarocks installation with "--local" option
make.sh: more strict bash
make.sh: updating list-exports only if a rock is installed
prettifier: add 'before_open_curly_brace' and 'before_closed_curly_brace', 'after_open_curly_brace', 'after_closed_curly_brace' hooks
prettifier: add 'cat' function for adding to the buffer
prettifier: add 'key_finish' hook
prettifier: add 'string_start' and 'string_finish', 'number_start', 'number_finish', 'boolean_start', 'boolean_finish' hooks
prettifier: add colorizing to 'key_start' hook
prettifier: add curly braces hooks calls
prettifier: add ldoc comments
prettifier: add local 'make_color_resetter' function: hook factory for adding reset color sequences
prettifier: add local 'make_colorizer' function: hook factory for adding color sequences
prettifier: fix according to luacheck warnings
prettifier: fix quotes style
prettifier: make_prettifier: add colors argument, check and store it in instance
prettifier: make_prettifier: check argument types
strict: add 'newproxy' to globals
strict: declare globals for Lua versions compatibility: loadstring and setfenv
tdeepequals/tless_kv: tmore does not need vis* initialization anymore
tdeepequals/tmore: always initializing p_table to prevent crashes in tless
tdeepequals: add ldoc comments for ordered_pairs, and ldoc comment stubs for the rest
test/cases/0080-functional: pass tests dependent on newproxy if newproxy not found
test/cases/0080-functional: use BROKEN_IF for tests that use newproxy
test/cases/0120-misc: add comments about failed test for unique_object, add BROKEN_IF condition
test/cases/0120-misc: fix tests with newproxy for Lua > 5.1
test/cases/0130-priority_queue: fix formatting
test/cases/0130-priority_queue: fix tests dependent on newproxy for Lua > 5.1
test/cases/0160-string: fix kv_concat tests
test/cases/0160-string: fix tjson_simple test
test/cases/0160-string: mark "tjson_simple" test as BROKEN if newproxy is not found
test/cases/0190-table-utils: fix tflip_inplace-many
test/cases/0190-table-utils: mark "tclone-nontable" test as BROKEN if newproxy is not found
test/cases/0204-tdeepequals-userdata-functions-threads: mark tests as BROKEN if newproxy is not found
test/cases/0240-type: mark "all_predicates" test as BROKEN if newproxy is not found
test/cases/0250-typeassert: mark "all_assertions" test as BROKEN if newproxy is not found
test/cases/0270-ensure: fix ensure_error_with_substring-is-happy-on-failure and ensure_error-is-happy-on-failure tests
test/cases/0290-test: fix "tstr table with keys" test
test/cases/0290-tstr: mark tests that dependent of newproxy as BROKEN if newproxy not found
test/cases/0330-tpretty: fix tpretty_ex-bug-concat-nil-full test
test/cases/{0420-code-foreign-globals-luajit2, 0430-code-foreign-globals-lua5_1}: pass tests if cannot load lua-aplicado shell module
test/cases/{0420-code-foreign-globals-luajit2, 0430-code-foreign-globals-lua5_1}: tests are BROKEN_IF cannot load lua-aplicado shell module
test/cases: add 0333-tpretty-color
test/cases: sets loadstring analog if loadstring is not found
test/cases{0160,0190}: tisarray_not
test/data/suite: add suites for BROKEN_IF tests
test/low-level/0150-strict: expect declared globals for Lua versions compatibility: loadstring and setfenv
test/low-level/0150-strict: fix broken test
test/suite/0171-suite-full: fix Complex factory function input test 2
test/suite: add 0174-suite-BROKEN_IF
test/test-lib/generate-test-list: fix lib_file
test/test-lib/tserialize-test-utils: fix loadstring for Lua > 5.1
test/test-lib/value_generators: fix formatting
test/test-lib/value_generators: throw error if newproxy not found
test/test-list: regenerated
test/test-list: regenerated
test/test.lua: redundant variable declaration removed
test/test.lua: whitespace
test/test: add footer for failed low-level tests error messages dump
test/test: use ad-hoc shell_read if lua-aplicado.shell not found
tpretty, tserialize, tstr: replace lua51_keywords with lua_keywords
tpretty: add 'key_finish' hook call
tpretty: add 'string_start' and 'string_finish', 'number_start', 'number_finish', 'boolean_start', 'boolean_finish' hook calls
tpretty: add colors as the last argument to tpretty, tpretty_ex, tpretty_ordered; pass colors to prettifier factory
tpretty: add ldoc comments
tpretty: disable colors for when rendering table key name
tpretty: fix quotes style
tpretty: remove excessive 'local' statement for already defined variable
tpretty: remove unused variables
{tpretty, test/cases/0330-tpretty}: fix serializing tables with overloaded __index
```

2021-04-26 08:51 UTC, agladysh requested changes

2021-04-26 08:51 UTC, agladysh commented on HISTORY
> +      Updating list-exports only if a rock is installed.
непонятно, что это значит

2021-04-26 08:51 UTC, agladysh commented on HISTORY
> +    Documentation is updated.
бестолковый ченджлог, конечно

много чего написано, а что это конкретно все значит — не ясно.

но видимо придется принять, сил дописывать нет

2021-04-26 08:51 UTC, merged