Lua 5.4 support
lua-nucleo/lua-nucleo pull request #59
Opened 2020-12-04 06:55 UTC by E-Fir

2020-12-04 07:57 UTC, agladysh requested changes

2020-12-04 07:57 UTC, agladysh commented on lua-nucleo/import.lua
>    local get_path
ПП

2020-12-04 07:57 UTC, agladysh commented on lua-nucleo/args.lua
> -              "argument #" .. ((i + 1) * 0.5) .. ": bad expected type `"
ПП

2020-12-04 07:57 UTC, agladysh commented on lua-nucleo/args.lua
> -              "argument #" .. ((i + 1) * 0.5) .. ": bad expected type `"
А почему это в этом PR?

2020-12-04 07:57 UTC, agladysh commented on lua-nucleo/ensure.lua
> +local ensure_strvariant = function(msg, actual, expected, ...)
Почему это  этом PR? Где тесты?

2020-12-04 07:57 UTC, agladysh commented on test/cases/0160-string.lua
> +      ensure_strvariant,
Почему это в этом PR?

2021-02-03 13:33 UTC, E-Fir commented
gone to https://github.com/lua-nucleo/lua-nucleo/pull/75 https://github.com/lua-nucleo/lua-nucleo/pull/75

2021-02-03 13:33 UTC, closed without merging