newproxy() usage fixes
lua-nucleo/lua-nucleo pull request #64
Opened 2020-12-10 08:24 UTC by E-Fir

2020-12-10 08:29 UTC, agladysh commented on test/cases/0120-misc.lua
> +    debug.setmetatable(
тут точно нужен debug?

2020-12-10 08:29 UTC, agladysh commented on test/cases/0120-misc.lua
> +    local table = { }
это обычно в одну строку пишем

2020-12-10 08:30 UTC, agladysh commented on test/test-lib/value_generators.lua
> +        xpcall(require, function() end,'newproxy')
пропущен пробел

2020-12-10 08:30 UTC, agladysh commented on test/test-lib/value_generators.lua
> +      invariant(
почему это в этом коммите?

2020-12-10 08:31 UTC, agladysh commented on test/test-lib/value_generators.lua
> +  error('newproxy is required for this module')
какой смысл делать выше xpcall, если ты тут же делаешь error? в итоге сжираешь диагностику от require

не надо так!

2020-12-10 08:38 UTC, agladysh requested changes

2020-12-10 08:38 UTC, agladysh commented on test/cases/0130-priority_queue.lua
> +  test:BROKEN "single-invalid-priority-type"
я бы предпочел обратную запись, когда негативный сценарий впереди — он короче

2020-12-10 08:39 UTC, agladysh commented on test/cases/0160-string.lua
> +if newproxy then
очень меня раздражает такая запись

может быть добавим какой-нибудь

test:IF(newproxy) "id" (function()
end)

который внутри будет broken вызывать?

(в имени IF не уверен)

2020-12-11 12:29 UTC, E-Fir commented on test/cases/0160-string.lua
> +if newproxy then
test:BROKEN_IF

2020-12-11 12:55 UTC, agladysh commented on test/cases/0160-string.lua
> +if newproxy then
test:BROKEN_IF(newproxy) — логика перевернута так

мы не сломаны если есть newproxy

2020-12-11 12:58 UTC, E-Fir commented on test/cases/0120-misc.lua
> +    local table = { }
не влезало в 80 символов в одну строку

2020-12-11 12:58 UTC, E-Fir commented on test/cases/0120-misc.lua
> +    debug.setmetatable(
не нужен

2020-12-11 12:59 UTC, agladysh commented on test/cases/0120-misc.lua
> +    local table = { }
что мешало разбить описание таблицы? :)

2020-12-11 12:59 UTC, agladysh commented on test/cases/0120-misc.lua
> +    debug.setmetatable(
тогда убери плз :)

2020-12-11 14:41 UTC, E-Fir commented on test/cases/0120-misc.lua
> +    local table = { }
ничего не мешало, но ничего и не сподвигало)

2020-12-11 15:01 UTC, E-Fir commented on test/cases/0160-string.lua
> +if newproxy then
test:BROKEN_IF(not newproxy)

2020-12-11 15:03 UTC, E-Fir commented on test/cases/0160-string.lua
> +if newproxy then
test:VALID_IF(newproxy)

2020-12-11 15:03 UTC, E-Fir commented on test/cases/0120-misc.lua
> +    debug.setmetatable(
тут вообще баг в 5.1 неожиданно был, исправил (а 5.1 нужно, дальше не нужно)

2020-12-11 15:04 UTC, E-Fir commented on test/test-lib/value_generators.lua
> +      invariant(
разделил

2020-12-11 15:04 UTC, E-Fir commented on test/test-lib/value_generators.lua
> +  error('newproxy is required for this module')
исправил

2020-12-11 15:04 UTC, E-Fir commented on test/cases/0130-priority_queue.lua
> +  test:BROKEN "single-invalid-priority-type"
заменил на BROKEN_IF

2020-12-11 15:05 UTC, E-Fir commented on test/cases/0160-string.lua
> +if newproxy then
заменил на BROKEN_IF

можно для удобства добавить и VALID_IF

2020-12-11 15:21 UTC, agladysh commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
а почему это требуется сейчас и не требовалось раньше?

2020-12-14 09:26 UTC, E-Fir commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
раньше был test:test_for, который устанавливал что для экспортной функции, имя которого заданного в параметре, тесты были

теперь заменили на test:BROKEN, который не устанавливает ничего такого

поэтому устанавливаем это с помощью test:tests_for

2020-12-14 09:32 UTC, agladysh commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
мы удалили test:BROKEN, не понимаю тебя

2020-12-15 09:25 UTC, E-Fir commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
имел ввиду на самом деле test:BROKEN_IF

2020-12-15 09:25 UTC, E-Fir commented on test/test-lib/value_generators.lua
> +  error('newproxy is required for this module')
тут всё ок теперь?

2020-12-15 09:34 UTC, agladysh commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
а разве `test:BROKEN_IF () "foo"` не должен вести себя как `test "foo"`

2021-01-13 12:46 UTC, E-Fir commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
должен, но раньше был не `test "foo"`, a `test:test_for "foo"`, отсюда и нестыковка

2021-01-13 12:48 UTC, E-Fir commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
```
-if newproxy then
-  test:test_for "identity" (function()

+test:tests_for "identity"
+test:BROKEN_IF(not newproxy) "identity" (function()
```

2021-01-13 13:18 UTC, agladysh commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
можем ли малой кровью это победить?

2021-01-25 13:23 UTC, E-Fir commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
Думаю, да. Какой варинат больше нравится?

```
test:BROKEN_IF(not newproxy):for_test "identity" (function()
end)
```

```
test:BROKEN_IF(not newproxy):test_for "identity" (function()
end)
```

```
test:test_for("identity"):BROKEN_IF(not newproxy)(function()
end)
```

```
test:test_for("identity"):BROKEN_IF(not newproxy):set(function()
end)
```

```
свой вариант
```

2021-01-25 13:45 UTC, agladysh commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
test_for, порядок вызовов, в идеале, не важен

то есть второй и третий должны работать

2021-01-29 08:04 UTC, E-Fir commented on test/cases/0080-functional.lua
> +test:tests_for "invariant"
готово

2021-01-29 09:06 UTC, merged