language: update to support all current Lua versions >= 5.1
lua-nucleo/lua-nucleo pull request #66
Opened 2020-12-10 12:47 UTC by E-Fir

2020-12-10 15:36 UTC, agladysh commented on lua-nucleo/args.lua
> +local lua_types = import 'lua-nucleo/language.lua' { 'lua_types' }
я не уверен, что это корректная правка, мы теряем возможность работать прицельно по 5.1

я бы сделал такую таблицу суперпозицией таблиц про 5.1-5.4

2020-12-10 15:37 UTC, agladysh commented on lua-nucleo/tstr.lua
> +            if not lua_keywords[k] and string_match(k, "^[%a_][%a%d_]*$") then
аналогично lua51_types

2020-12-10 15:37 UTC, agladysh commented on lua-nucleo/language.lua
> +return language
ага, а ты такую суперпозицию и сделал... хммм... но почему оно зависит от версии интерпретатора?

2021-01-13 12:20 UTC, E-Fir commented on lua-nucleo/args.lua
> +local lua_types = import 'lua-nucleo/language.lua' { 'lua_types' }
если нужна возможность прицельно работать по 5.1 не из 5.1, то можно экспортов добавить в language

2021-01-13 12:21 UTC, E-Fir commented on lua-nucleo/language.lua
> +return language
повторяет оригинальное поведение

2021-01-13 13:23 UTC, agladysh commented on lua-nucleo/args.lua
> +local lua_types = import 'lua-nucleo/language.lua' { 'lua_types' }
Да, нужна

2021-01-13 13:23 UTC, agladysh commented on lua-nucleo/language.lua
> +return language
Дай плз на него ссылку

2021-01-25 12:53 UTC, E-Fir commented on lua-nucleo/language.lua
> +return language
https://github.com/lua-nucleo/lua-nucleo/blob/master/lua-nucleo/language.lua

2021-01-25 13:05 UTC, E-Fir commented on lua-nucleo/args.lua
> +local lua_types = import 'lua-nucleo/language.lua' { 'lua_types' }
так, а экспорты то я делал с самого начала для всего, вылетело из головы)

в итоге, здесь мы не теряем возможность прицелоьно работать по какой-либо версии

можем, если хотим, написать

```
local lua51_types = import 'lua-nucleo/language.lua' { 'lua51_types' }
local lua52_types = import 'lua-nucleo/language.lua' { 'lua52_types' }
local lua53_types = import 'lua-nucleo/language.lua' { 'lua53_types' }
local lua54_types = import 'lua-nucleo/language.lua' { 'lua54_types' }

local lua54_keywords = import 'lua-nucleo/language.lua' { 'lua54_keywords' }
```

2021-01-25 13:07 UTC, E-Fir commented on lua-nucleo/tstr.lua
> +            if not lua_keywords[k] and string_match(k, "^[%a_][%a%d_]*$") then
используются кейворды для текущей версии луа

возможность использовать версию прицельно тоже есть

2021-01-25 13:45 UTC, agladysh commented on lua-nucleo/args.lua
> +local lua_types = import 'lua-nucleo/language.lua' { 'lua_types' }
отлично

2021-01-25 13:47 UTC, agladysh requested changes

2021-01-25 13:47 UTC, agladysh commented on lua-nucleo/language.lua
> +return language
я не очень понял

где мы в оригинальном поведении смотрим на _VERSION?

2021-01-25 13:50 UTC, E-Fir commented on lua-nucleo/language.lua
> +return language
Имел ввиду "поведение" `return`.

В оригинале мы не смотрим на _VERSION, но возвращаем типы и кейворды для текущей версии Lua. 

Здесь сделал по аналогии и дополнительно есть обратная совместимость. lua51_types и lua51_keywords по прежнему на месте

2021-01-25 15:21 UTC, E-Fir commented on lua-nucleo/language.lua
> +return language
Alexander Gladysh  1 hour ago
это дискуссионный вопрос
Alexander Gladysh  1 hour ago
можно сказать, что мы возвращаем кейворды текущей версии, поскольку код работает только под 5.1
Alexey Romanov  1 hour ago
да
Alexey Romanov  1 hour ago
именно
Alexey Romanov  1 hour ago
в оригинале
Alexander Gladysh  1 hour ago
а можно сказать, что мы возвращаем кейворды строго 5.1, потому, что именно это мы и делаем
Alexander Gladysh  1 hour ago
в общем, ты поменял (уточнил) контракт модулядокументируй его плз в коде лдоком
Alexander Gladysh  1 hour ago
и оставь так
Alexey Romanov  1 hour ago
уточнил
Alexey Romanov  1 hour ago
хорошо

2021-01-27 09:40 UTC, E-Fir commented on lua-nucleo/language.lua
> +return language
готово

2021-01-27 11:10 UTC, agladysh commented on lua-nucleo/language.lua
> +-- for documentation purposes only:
а почему так фигурно?

2021-01-27 15:33 UTC, E-Fir commented on lua-nucleo/language.lua
> +-- for documentation purposes only:
если я правильно понимаю вопрос, то потому, что по-другому очень всё криво выходило, этот вариант самы боле мене в итоге получился.

2021-01-27 16:45 UTC, E-Fir commented on lua-nucleo/language.lua
> +-- for documentation purposes only:
чтобы не делать бесползеной работы процессору и сборщику мусора для объектов, которые только для документации нужны

хотя я не знаю как точно работает луа и будет ли вышеупомянутая работа происходить на самом деле, привычки подсказали написать такую конструкцию

2021-01-27 17:04 UTC, agladysh commented on lua-nucleo/language.lua
> +-- for documentation purposes only:
Не оптимизирует.

Но я спрашиваю не про это. Почему ты не документировал экспортируемые из модуля значения по месту?

2021-01-28 04:48 UTC, E-Fir commented on lua-nucleo/language.lua
> +-- for documentation purposes only:
Потому что это выглядит менее привлекательным. Сначала я и начал делать по месту, но пришел к варианту как сейчас.

Пример:

```
--- Hashset of Lua 5.1 language keywords (table where the key is a keyword
-- string and the value is the `true` boolean).
local lua51_keywords =
{
  ["and"] = true,    ["break"] = true,  ["do"] = true,
  ["else"] = true,   ["elseif"] = true, ["end"] = true,
  ["false"] = true,  ["for"] = true,    ["function"] = true,
  ["if"] = true,     ["in"] = true,     ["local"] = true,
  ["nil"] = true,    ["not"] = true,    ["or"] = true,
  ["repeat"] = true, ["return"] = true, ["then"] = true,
  ["true"] = true,    ["until"] = true,  ["while"] = true
}
```

В доку lua51_keywords попадают все ключи таблицы, а мне это не надо. Поэтому надо или как-то указывать, что ключи надо пропускать или ещё как-то ухитряться сделать, чтобы они не попали в доку.

```
--- Hashset of Lua 5.2 language keywords (table where the key is a keyword
-- string and the value is the `true` boolean).
local lua52_keywords = { ["goto"] = true }
for k, _ in pairs(lua51_keywords) do
  lua52_keywords[k] = true
end
```

Почти аналогично предыдущему, но попадает только один ключ `goto`.

Чтобы задокументировать `lua53_keywords` мне нужно добавлять, например, дополнительную локальную переменную:

```
--- Hashset of Lua 5.3 language keywords (table where the key is a keyword
-- string and the value is the `true` boolean).
local lua53_keywords = lua52_keywords
```

Мне не нравится добавлять работу коду только из-за того, чтобы задокументировать по месту.

Документировать через экспортируюемую таблицу адекватно тоже не вышло.

2021-01-29 09:05 UTC, agladysh commented on lua-nucleo/language.lua
> +-- for documentation purposes only:
Меня это не устраивает, но давай больше не будем тратить время.

2021-01-29 09:05 UTC, merged